// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: clusters.sql

package querier

import (
	"context"
)

const createCluster = `-- name: CreateCluster :one
INSERT INTO clusters (
    org_id,
    name,
    host,
    sql_port,
    meta_port,
    http_port,
    version, 
    metrics_store_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, org_id, name, host, sql_port, meta_port, http_port, version, created_at, updated_at, metrics_store_id
`

type CreateClusterParams struct {
	OrgID          int32
	Name           string
	Host           string
	SqlPort        int32
	MetaPort       int32
	HttpPort       int32
	Version        string
	MetricsStoreID *int32
}

func (q *Queries) CreateCluster(ctx context.Context, arg CreateClusterParams) (*Cluster, error) {
	row := q.db.QueryRow(ctx, createCluster,
		arg.OrgID,
		arg.Name,
		arg.Host,
		arg.SqlPort,
		arg.MetaPort,
		arg.HttpPort,
		arg.Version,
		arg.MetricsStoreID,
	)
	var i Cluster
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Host,
		&i.SqlPort,
		&i.MetaPort,
		&i.HttpPort,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MetricsStoreID,
	)
	return &i, err
}

const deleteOrgCluster = `-- name: DeleteOrgCluster :exec
DELETE FROM clusters
WHERE id = $1 AND org_id = $2
`

type DeleteOrgClusterParams struct {
	ID    int32
	OrgID int32
}

func (q *Queries) DeleteOrgCluster(ctx context.Context, arg DeleteOrgClusterParams) error {
	_, err := q.db.Exec(ctx, deleteOrgCluster, arg.ID, arg.OrgID)
	return err
}

const getClusterByID = `-- name: GetClusterByID :one
SELECT id, org_id, name, host, sql_port, meta_port, http_port, version, created_at, updated_at, metrics_store_id FROM clusters
WHERE id = $1
`

func (q *Queries) GetClusterByID(ctx context.Context, id int32) (*Cluster, error) {
	row := q.db.QueryRow(ctx, getClusterByID, id)
	var i Cluster
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Host,
		&i.SqlPort,
		&i.MetaPort,
		&i.HttpPort,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MetricsStoreID,
	)
	return &i, err
}

const getOrgCluster = `-- name: GetOrgCluster :one
SELECT id, org_id, name, host, sql_port, meta_port, http_port, version, created_at, updated_at, metrics_store_id FROM clusters
WHERE id = $1 AND org_id = $2
`

type GetOrgClusterParams struct {
	ID    int32
	OrgID int32
}

func (q *Queries) GetOrgCluster(ctx context.Context, arg GetOrgClusterParams) (*Cluster, error) {
	row := q.db.QueryRow(ctx, getOrgCluster, arg.ID, arg.OrgID)
	var i Cluster
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Host,
		&i.SqlPort,
		&i.MetaPort,
		&i.HttpPort,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MetricsStoreID,
	)
	return &i, err
}

const initCluster = `-- name: InitCluster :one
INSERT INTO clusters (
    org_id,
    name,
    host,
    sql_port,
    meta_port,
    http_port,
    version,
    metrics_store_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) ON CONFLICT (org_id, name) DO UPDATE 
    SET 
        host = EXCLUDED.host,
        sql_port = EXCLUDED.sql_port,
        meta_port = EXCLUDED.meta_port,
        http_port = EXCLUDED.http_port,
        version = EXCLUDED.version,
        metrics_store_id = EXCLUDED.metrics_store_id,
        updated_at = CURRENT_TIMESTAMP
RETURNING id, org_id, name, host, sql_port, meta_port, http_port, version, created_at, updated_at, metrics_store_id
`

type InitClusterParams struct {
	OrgID          int32
	Name           string
	Host           string
	SqlPort        int32
	MetaPort       int32
	HttpPort       int32
	Version        string
	MetricsStoreID *int32
}

func (q *Queries) InitCluster(ctx context.Context, arg InitClusterParams) (*Cluster, error) {
	row := q.db.QueryRow(ctx, initCluster,
		arg.OrgID,
		arg.Name,
		arg.Host,
		arg.SqlPort,
		arg.MetaPort,
		arg.HttpPort,
		arg.Version,
		arg.MetricsStoreID,
	)
	var i Cluster
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Host,
		&i.SqlPort,
		&i.MetaPort,
		&i.HttpPort,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MetricsStoreID,
	)
	return &i, err
}

const listClustersByMetricsStoreID = `-- name: ListClustersByMetricsStoreID :many
SELECT id, org_id, name, host, sql_port, meta_port, http_port, version, created_at, updated_at, metrics_store_id FROM clusters
WHERE metrics_store_id = $1
ORDER BY name
`

func (q *Queries) ListClustersByMetricsStoreID(ctx context.Context, metricsStoreID *int32) ([]*Cluster, error) {
	rows, err := q.db.Query(ctx, listClustersByMetricsStoreID, metricsStoreID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Cluster
	for rows.Next() {
		var i Cluster
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Host,
			&i.SqlPort,
			&i.MetaPort,
			&i.HttpPort,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MetricsStoreID,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrgClusters = `-- name: ListOrgClusters :many
SELECT id, org_id, name, host, sql_port, meta_port, http_port, version, created_at, updated_at, metrics_store_id FROM clusters
WHERE org_id = $1
ORDER BY name
`

func (q *Queries) ListOrgClusters(ctx context.Context, orgID int32) ([]*Cluster, error) {
	rows, err := q.db.Query(ctx, listOrgClusters, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Cluster
	for rows.Next() {
		var i Cluster
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Host,
			&i.SqlPort,
			&i.MetaPort,
			&i.HttpPort,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MetricsStoreID,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeClusterMetricsStoreID = `-- name: RemoveClusterMetricsStoreID :exec
UPDATE clusters
SET metrics_store_id = NULL
WHERE id = $1 AND org_id = $2
`

type RemoveClusterMetricsStoreIDParams struct {
	ID    int32
	OrgID int32
}

func (q *Queries) RemoveClusterMetricsStoreID(ctx context.Context, arg RemoveClusterMetricsStoreIDParams) error {
	_, err := q.db.Exec(ctx, removeClusterMetricsStoreID, arg.ID, arg.OrgID)
	return err
}

const updateOrgCluster = `-- name: UpdateOrgCluster :one
UPDATE clusters
SET
    name = $3,
    host = $4,
    sql_port = $5,
    meta_port = $6,
    http_port = $7,
    version = $8,
    metrics_store_id = $9,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND org_id = $2
RETURNING id, org_id, name, host, sql_port, meta_port, http_port, version, created_at, updated_at, metrics_store_id
`

type UpdateOrgClusterParams struct {
	ID             int32
	OrgID          int32
	Name           string
	Host           string
	SqlPort        int32
	MetaPort       int32
	HttpPort       int32
	Version        string
	MetricsStoreID *int32
}

func (q *Queries) UpdateOrgCluster(ctx context.Context, arg UpdateOrgClusterParams) (*Cluster, error) {
	row := q.db.QueryRow(ctx, updateOrgCluster,
		arg.ID,
		arg.OrgID,
		arg.Name,
		arg.Host,
		arg.SqlPort,
		arg.MetaPort,
		arg.HttpPort,
		arg.Version,
		arg.MetricsStoreID,
	)
	var i Cluster
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Host,
		&i.SqlPort,
		&i.MetaPort,
		&i.HttpPort,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MetricsStoreID,
	)
	return &i, err
}
