// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package querier

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/risingwavelabs/wavekit/pkg/zgen/apigen"
)

type AutoBackupConfig struct {
	ClusterID int32
	Enabled   bool
	CreatedAt time.Time
	UpdatedAt time.Time
	TaskID    int32
}

type AutoDiagnosticsConfig struct {
	ClusterID int32
	Enabled   bool
	CreatedAt time.Time
	UpdatedAt time.Time
	TaskID    int32
}

type Cluster struct {
	ID             int32
	OrgID          int32
	Name           string
	Host           string
	SqlPort        int32
	MetaPort       int32
	HttpPort       int32
	Version        string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	MetricsStoreID *int32
}

type ClusterDiagnostic struct {
	ID        int32
	ClusterID int32
	Content   string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type ClusterSnapshot struct {
	ClusterID  int32
	SnapshotID int64
	Name       string
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type DatabaseConnection struct {
	ID        int32
	OrgID     int32
	Name      string
	ClusterID int32
	Username  string
	Password  *string
	Database  string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type MetricsStore struct {
	ID            int32
	Name          string
	Spec          *apigen.MetricsStoreSpec
	OrgID         int32
	DefaultLabels *apigen.MetricsStoreLabelMatcherList
	CreatedAt     pgtype.Timestamp
	UpdatedAt     pgtype.Timestamp
}

type OpaqueKey struct {
	ID        int64
	Key       []byte
	UserID    int32
	CreatedAt time.Time
	UpdatedAt time.Time
}

type OrgSetting struct {
	OrgID     int32
	Timezone  string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Organization struct {
	ID        int32
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
	Timezone  string
}

type OrganizationOwner struct {
	UserID         int32
	OrganizationID int32
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type RefreshToken struct {
	ID        int32
	UserID    int32
	Token     string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Snapshot struct {
	ClusterID  int32
	SnapshotID int64
	CreatedAt  time.Time
}

type User struct {
	ID             int32
	Name           string
	PasswordHash   string
	PasswordSalt   string
	OrganizationID int32
	CreatedAt      time.Time
	UpdatedAt      time.Time
}
