// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: org_settings.sql

package querier

import (
	"context"
)

const createOrgSettings = `-- name: CreateOrgSettings :exec
INSERT INTO org_settings (org_id, timezone)
VALUES ($1, $2)
`

type CreateOrgSettingsParams struct {
	OrgID    int32
	Timezone string
}

func (q *Queries) CreateOrgSettings(ctx context.Context, arg CreateOrgSettingsParams) error {
	_, err := q.db.Exec(ctx, createOrgSettings, arg.OrgID, arg.Timezone)
	return err
}

const getOrgSettings = `-- name: GetOrgSettings :one
SELECT org_id, timezone, created_at, updated_at FROM org_settings
WHERE org_id = $1
`

func (q *Queries) GetOrgSettings(ctx context.Context, orgID int32) (*OrgSetting, error) {
	row := q.db.QueryRow(ctx, getOrgSettings, orgID)
	var i OrgSetting
	err := row.Scan(
		&i.OrgID,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
