// Code generated by MockGen. DO NOT EDIT.
// Source: internal/model/model.go
//
// Generated by this command:
//
//	mockgen -source=internal/model/model.go -destination=internal/model/mock_gen.go -package=model
//

// Package model is a generated GoMock package.
package model

import (
	context "context"
	reflect "reflect"

	apigen "github.com/risingwavelabs/wavekit/internal/apigen"
	querier "github.com/risingwavelabs/wavekit/internal/model/querier"
	gomock "go.uber.org/mock/gomock"
)

// MockModelInterface is a mock of ModelInterface interface.
type MockModelInterface struct {
	ctrl     *gomock.Controller
	recorder *MockModelInterfaceMockRecorder
	isgomock struct{}
}

// MockModelInterfaceMockRecorder is the mock recorder for MockModelInterface.
type MockModelInterfaceMockRecorder struct {
	mock *MockModelInterface
}

// NewMockModelInterface creates a new mock instance.
func NewMockModelInterface(ctrl *gomock.Controller) *MockModelInterface {
	mock := &MockModelInterface{ctrl: ctrl}
	mock.recorder = &MockModelInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockModelInterface) EXPECT() *MockModelInterfaceMockRecorder {
	return m.recorder
}

// CreateAutoBackupConfig mocks base method.
func (m *MockModelInterface) CreateAutoBackupConfig(ctx context.Context, arg querier.CreateAutoBackupConfigParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAutoBackupConfig", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateAutoBackupConfig indicates an expected call of CreateAutoBackupConfig.
func (mr *MockModelInterfaceMockRecorder) CreateAutoBackupConfig(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAutoBackupConfig", reflect.TypeOf((*MockModelInterface)(nil).CreateAutoBackupConfig), ctx, arg)
}

// CreateAutoDiagnosticsConfig mocks base method.
func (m *MockModelInterface) CreateAutoDiagnosticsConfig(ctx context.Context, arg querier.CreateAutoDiagnosticsConfigParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAutoDiagnosticsConfig", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateAutoDiagnosticsConfig indicates an expected call of CreateAutoDiagnosticsConfig.
func (mr *MockModelInterfaceMockRecorder) CreateAutoDiagnosticsConfig(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAutoDiagnosticsConfig", reflect.TypeOf((*MockModelInterface)(nil).CreateAutoDiagnosticsConfig), ctx, arg)
}

// CreateCluster mocks base method.
func (m *MockModelInterface) CreateCluster(ctx context.Context, arg querier.CreateClusterParams) (*querier.Cluster, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCluster", ctx, arg)
	ret0, _ := ret[0].(*querier.Cluster)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCluster indicates an expected call of CreateCluster.
func (mr *MockModelInterfaceMockRecorder) CreateCluster(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCluster", reflect.TypeOf((*MockModelInterface)(nil).CreateCluster), ctx, arg)
}

// CreateClusterDiagnostic mocks base method.
func (m *MockModelInterface) CreateClusterDiagnostic(ctx context.Context, arg querier.CreateClusterDiagnosticParams) (*querier.ClusterDiagnostic, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateClusterDiagnostic", ctx, arg)
	ret0, _ := ret[0].(*querier.ClusterDiagnostic)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateClusterDiagnostic indicates an expected call of CreateClusterDiagnostic.
func (mr *MockModelInterfaceMockRecorder) CreateClusterDiagnostic(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateClusterDiagnostic", reflect.TypeOf((*MockModelInterface)(nil).CreateClusterDiagnostic), ctx, arg)
}

// CreateClusterSnapshot mocks base method.
func (m *MockModelInterface) CreateClusterSnapshot(ctx context.Context, arg querier.CreateClusterSnapshotParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateClusterSnapshot", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateClusterSnapshot indicates an expected call of CreateClusterSnapshot.
func (mr *MockModelInterfaceMockRecorder) CreateClusterSnapshot(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateClusterSnapshot", reflect.TypeOf((*MockModelInterface)(nil).CreateClusterSnapshot), ctx, arg)
}

// CreateDatabaseConnection mocks base method.
func (m *MockModelInterface) CreateDatabaseConnection(ctx context.Context, arg querier.CreateDatabaseConnectionParams) (*querier.DatabaseConnection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDatabaseConnection", ctx, arg)
	ret0, _ := ret[0].(*querier.DatabaseConnection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateDatabaseConnection indicates an expected call of CreateDatabaseConnection.
func (mr *MockModelInterfaceMockRecorder) CreateDatabaseConnection(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDatabaseConnection", reflect.TypeOf((*MockModelInterface)(nil).CreateDatabaseConnection), ctx, arg)
}

// CreateMetricsStore mocks base method.
func (m *MockModelInterface) CreateMetricsStore(ctx context.Context, arg querier.CreateMetricsStoreParams) (*querier.MetricsStore, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMetricsStore", ctx, arg)
	ret0, _ := ret[0].(*querier.MetricsStore)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateMetricsStore indicates an expected call of CreateMetricsStore.
func (mr *MockModelInterfaceMockRecorder) CreateMetricsStore(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMetricsStore", reflect.TypeOf((*MockModelInterface)(nil).CreateMetricsStore), ctx, arg)
}

// CreateOrganization mocks base method.
func (m *MockModelInterface) CreateOrganization(ctx context.Context, name string) (*querier.Organization, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrganization", ctx, name)
	ret0, _ := ret[0].(*querier.Organization)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOrganization indicates an expected call of CreateOrganization.
func (mr *MockModelInterfaceMockRecorder) CreateOrganization(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrganization", reflect.TypeOf((*MockModelInterface)(nil).CreateOrganization), ctx, name)
}

// CreateOrganizationOwner mocks base method.
func (m *MockModelInterface) CreateOrganizationOwner(ctx context.Context, arg querier.CreateOrganizationOwnerParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrganizationOwner", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateOrganizationOwner indicates an expected call of CreateOrganizationOwner.
func (mr *MockModelInterfaceMockRecorder) CreateOrganizationOwner(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrganizationOwner", reflect.TypeOf((*MockModelInterface)(nil).CreateOrganizationOwner), ctx, arg)
}

// CreateSnapshot mocks base method.
func (m *MockModelInterface) CreateSnapshot(ctx context.Context, arg querier.CreateSnapshotParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSnapshot", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateSnapshot indicates an expected call of CreateSnapshot.
func (mr *MockModelInterfaceMockRecorder) CreateSnapshot(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSnapshot", reflect.TypeOf((*MockModelInterface)(nil).CreateSnapshot), ctx, arg)
}

// CreateTask mocks base method.
func (m *MockModelInterface) CreateTask(ctx context.Context, arg querier.CreateTaskParams) (*querier.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTask", ctx, arg)
	ret0, _ := ret[0].(*querier.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTask indicates an expected call of CreateTask.
func (mr *MockModelInterfaceMockRecorder) CreateTask(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTask", reflect.TypeOf((*MockModelInterface)(nil).CreateTask), ctx, arg)
}

// CreateUser mocks base method.
func (m *MockModelInterface) CreateUser(ctx context.Context, arg querier.CreateUserParams) (*querier.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, arg)
	ret0, _ := ret[0].(*querier.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockModelInterfaceMockRecorder) CreateUser(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockModelInterface)(nil).CreateUser), ctx, arg)
}

// DeleteAllOrgDatabaseConnectionsByClusterID mocks base method.
func (m *MockModelInterface) DeleteAllOrgDatabaseConnectionsByClusterID(ctx context.Context, arg querier.DeleteAllOrgDatabaseConnectionsByClusterIDParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAllOrgDatabaseConnectionsByClusterID", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAllOrgDatabaseConnectionsByClusterID indicates an expected call of DeleteAllOrgDatabaseConnectionsByClusterID.
func (mr *MockModelInterfaceMockRecorder) DeleteAllOrgDatabaseConnectionsByClusterID(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAllOrgDatabaseConnectionsByClusterID", reflect.TypeOf((*MockModelInterface)(nil).DeleteAllOrgDatabaseConnectionsByClusterID), ctx, arg)
}

// DeleteClusterSnapshot mocks base method.
func (m *MockModelInterface) DeleteClusterSnapshot(ctx context.Context, arg querier.DeleteClusterSnapshotParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteClusterSnapshot", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteClusterSnapshot indicates an expected call of DeleteClusterSnapshot.
func (mr *MockModelInterfaceMockRecorder) DeleteClusterSnapshot(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteClusterSnapshot", reflect.TypeOf((*MockModelInterface)(nil).DeleteClusterSnapshot), ctx, arg)
}

// DeleteMetricsStore mocks base method.
func (m *MockModelInterface) DeleteMetricsStore(ctx context.Context, arg querier.DeleteMetricsStoreParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMetricsStore", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteMetricsStore indicates an expected call of DeleteMetricsStore.
func (mr *MockModelInterfaceMockRecorder) DeleteMetricsStore(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMetricsStore", reflect.TypeOf((*MockModelInterface)(nil).DeleteMetricsStore), ctx, arg)
}

// DeleteOrgCluster mocks base method.
func (m *MockModelInterface) DeleteOrgCluster(ctx context.Context, arg querier.DeleteOrgClusterParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOrgCluster", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteOrgCluster indicates an expected call of DeleteOrgCluster.
func (mr *MockModelInterfaceMockRecorder) DeleteOrgCluster(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOrgCluster", reflect.TypeOf((*MockModelInterface)(nil).DeleteOrgCluster), ctx, arg)
}

// DeleteOrgDatabaseConnection mocks base method.
func (m *MockModelInterface) DeleteOrgDatabaseConnection(ctx context.Context, arg querier.DeleteOrgDatabaseConnectionParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOrgDatabaseConnection", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteOrgDatabaseConnection indicates an expected call of DeleteOrgDatabaseConnection.
func (mr *MockModelInterfaceMockRecorder) DeleteOrgDatabaseConnection(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOrgDatabaseConnection", reflect.TypeOf((*MockModelInterface)(nil).DeleteOrgDatabaseConnection), ctx, arg)
}

// DeleteOrganization mocks base method.
func (m *MockModelInterface) DeleteOrganization(ctx context.Context, id int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOrganization", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteOrganization indicates an expected call of DeleteOrganization.
func (mr *MockModelInterfaceMockRecorder) DeleteOrganization(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOrganization", reflect.TypeOf((*MockModelInterface)(nil).DeleteOrganization), ctx, id)
}

// DeleteRefreshToken mocks base method.
func (m *MockModelInterface) DeleteRefreshToken(ctx context.Context, arg querier.DeleteRefreshTokenParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRefreshToken", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRefreshToken indicates an expected call of DeleteRefreshToken.
func (mr *MockModelInterfaceMockRecorder) DeleteRefreshToken(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRefreshToken", reflect.TypeOf((*MockModelInterface)(nil).DeleteRefreshToken), ctx, arg)
}

// DeleteSnapshot mocks base method.
func (m *MockModelInterface) DeleteSnapshot(ctx context.Context, arg querier.DeleteSnapshotParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSnapshot", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSnapshot indicates an expected call of DeleteSnapshot.
func (mr *MockModelInterfaceMockRecorder) DeleteSnapshot(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSnapshot", reflect.TypeOf((*MockModelInterface)(nil).DeleteSnapshot), ctx, arg)
}

// DeleteUserByName mocks base method.
func (m *MockModelInterface) DeleteUserByName(ctx context.Context, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUserByName", ctx, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUserByName indicates an expected call of DeleteUserByName.
func (mr *MockModelInterfaceMockRecorder) DeleteUserByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUserByName", reflect.TypeOf((*MockModelInterface)(nil).DeleteUserByName), ctx, name)
}

// GetAllOrgDatabseConnectionsByClusterID mocks base method.
func (m *MockModelInterface) GetAllOrgDatabseConnectionsByClusterID(ctx context.Context, arg querier.GetAllOrgDatabseConnectionsByClusterIDParams) ([]*querier.DatabaseConnection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllOrgDatabseConnectionsByClusterID", ctx, arg)
	ret0, _ := ret[0].([]*querier.DatabaseConnection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllOrgDatabseConnectionsByClusterID indicates an expected call of GetAllOrgDatabseConnectionsByClusterID.
func (mr *MockModelInterfaceMockRecorder) GetAllOrgDatabseConnectionsByClusterID(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllOrgDatabseConnectionsByClusterID", reflect.TypeOf((*MockModelInterface)(nil).GetAllOrgDatabseConnectionsByClusterID), ctx, arg)
}

// GetAutoBackupConfig mocks base method.
func (m *MockModelInterface) GetAutoBackupConfig(ctx context.Context, clusterID int32) (*querier.AutoBackupConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAutoBackupConfig", ctx, clusterID)
	ret0, _ := ret[0].(*querier.AutoBackupConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAutoBackupConfig indicates an expected call of GetAutoBackupConfig.
func (mr *MockModelInterfaceMockRecorder) GetAutoBackupConfig(ctx, clusterID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAutoBackupConfig", reflect.TypeOf((*MockModelInterface)(nil).GetAutoBackupConfig), ctx, clusterID)
}

// GetAutoDiagnosticsConfig mocks base method.
func (m *MockModelInterface) GetAutoDiagnosticsConfig(ctx context.Context, clusterID int32) (*querier.AutoDiagnosticsConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAutoDiagnosticsConfig", ctx, clusterID)
	ret0, _ := ret[0].(*querier.AutoDiagnosticsConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAutoDiagnosticsConfig indicates an expected call of GetAutoDiagnosticsConfig.
func (mr *MockModelInterfaceMockRecorder) GetAutoDiagnosticsConfig(ctx, clusterID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAutoDiagnosticsConfig", reflect.TypeOf((*MockModelInterface)(nil).GetAutoDiagnosticsConfig), ctx, clusterID)
}

// GetClusterByID mocks base method.
func (m *MockModelInterface) GetClusterByID(ctx context.Context, id int32) (*querier.Cluster, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClusterByID", ctx, id)
	ret0, _ := ret[0].(*querier.Cluster)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetClusterByID indicates an expected call of GetClusterByID.
func (mr *MockModelInterfaceMockRecorder) GetClusterByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClusterByID", reflect.TypeOf((*MockModelInterface)(nil).GetClusterByID), ctx, id)
}

// GetClusterDiagnostic mocks base method.
func (m *MockModelInterface) GetClusterDiagnostic(ctx context.Context, id int32) (*querier.ClusterDiagnostic, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClusterDiagnostic", ctx, id)
	ret0, _ := ret[0].(*querier.ClusterDiagnostic)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetClusterDiagnostic indicates an expected call of GetClusterDiagnostic.
func (mr *MockModelInterfaceMockRecorder) GetClusterDiagnostic(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClusterDiagnostic", reflect.TypeOf((*MockModelInterface)(nil).GetClusterDiagnostic), ctx, id)
}

// GetDatabaseConnectionByID mocks base method.
func (m *MockModelInterface) GetDatabaseConnectionByID(ctx context.Context, id int32) (*querier.DatabaseConnection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDatabaseConnectionByID", ctx, id)
	ret0, _ := ret[0].(*querier.DatabaseConnection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDatabaseConnectionByID indicates an expected call of GetDatabaseConnectionByID.
func (mr *MockModelInterfaceMockRecorder) GetDatabaseConnectionByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDatabaseConnectionByID", reflect.TypeOf((*MockModelInterface)(nil).GetDatabaseConnectionByID), ctx, id)
}

// GetMetricsStore mocks base method.
func (m *MockModelInterface) GetMetricsStore(ctx context.Context, id int32) (*querier.MetricsStore, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMetricsStore", ctx, id)
	ret0, _ := ret[0].(*querier.MetricsStore)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMetricsStore indicates an expected call of GetMetricsStore.
func (mr *MockModelInterfaceMockRecorder) GetMetricsStore(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMetricsStore", reflect.TypeOf((*MockModelInterface)(nil).GetMetricsStore), ctx, id)
}

// GetMetricsStoreByIDAndOrgID mocks base method.
func (m *MockModelInterface) GetMetricsStoreByIDAndOrgID(ctx context.Context, arg querier.GetMetricsStoreByIDAndOrgIDParams) (*querier.MetricsStore, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMetricsStoreByIDAndOrgID", ctx, arg)
	ret0, _ := ret[0].(*querier.MetricsStore)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMetricsStoreByIDAndOrgID indicates an expected call of GetMetricsStoreByIDAndOrgID.
func (mr *MockModelInterfaceMockRecorder) GetMetricsStoreByIDAndOrgID(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMetricsStoreByIDAndOrgID", reflect.TypeOf((*MockModelInterface)(nil).GetMetricsStoreByIDAndOrgID), ctx, arg)
}

// GetOrgCluster mocks base method.
func (m *MockModelInterface) GetOrgCluster(ctx context.Context, arg querier.GetOrgClusterParams) (*querier.Cluster, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrgCluster", ctx, arg)
	ret0, _ := ret[0].(*querier.Cluster)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrgCluster indicates an expected call of GetOrgCluster.
func (mr *MockModelInterfaceMockRecorder) GetOrgCluster(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrgCluster", reflect.TypeOf((*MockModelInterface)(nil).GetOrgCluster), ctx, arg)
}

// GetOrgDatabaseByID mocks base method.
func (m *MockModelInterface) GetOrgDatabaseByID(ctx context.Context, arg querier.GetOrgDatabaseByIDParams) (*querier.DatabaseConnection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrgDatabaseByID", ctx, arg)
	ret0, _ := ret[0].(*querier.DatabaseConnection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrgDatabaseByID indicates an expected call of GetOrgDatabaseByID.
func (mr *MockModelInterfaceMockRecorder) GetOrgDatabaseByID(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrgDatabaseByID", reflect.TypeOf((*MockModelInterface)(nil).GetOrgDatabaseByID), ctx, arg)
}

// GetOrgDatabaseConnection mocks base method.
func (m *MockModelInterface) GetOrgDatabaseConnection(ctx context.Context, arg querier.GetOrgDatabaseConnectionParams) (*querier.DatabaseConnection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrgDatabaseConnection", ctx, arg)
	ret0, _ := ret[0].(*querier.DatabaseConnection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrgDatabaseConnection indicates an expected call of GetOrgDatabaseConnection.
func (mr *MockModelInterfaceMockRecorder) GetOrgDatabaseConnection(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrgDatabaseConnection", reflect.TypeOf((*MockModelInterface)(nil).GetOrgDatabaseConnection), ctx, arg)
}

// GetOrganization mocks base method.
func (m *MockModelInterface) GetOrganization(ctx context.Context, id int32) (*querier.Organization, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrganization", ctx, id)
	ret0, _ := ret[0].(*querier.Organization)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrganization indicates an expected call of GetOrganization.
func (mr *MockModelInterfaceMockRecorder) GetOrganization(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrganization", reflect.TypeOf((*MockModelInterface)(nil).GetOrganization), ctx, id)
}

// GetRefreshToken mocks base method.
func (m *MockModelInterface) GetRefreshToken(ctx context.Context, arg querier.GetRefreshTokenParams) (*querier.RefreshToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRefreshToken", ctx, arg)
	ret0, _ := ret[0].(*querier.RefreshToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRefreshToken indicates an expected call of GetRefreshToken.
func (mr *MockModelInterfaceMockRecorder) GetRefreshToken(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRefreshToken", reflect.TypeOf((*MockModelInterface)(nil).GetRefreshToken), ctx, arg)
}

// GetTaskByID mocks base method.
func (m *MockModelInterface) GetTaskByID(ctx context.Context, id int32) (*querier.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTaskByID", ctx, id)
	ret0, _ := ret[0].(*querier.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTaskByID indicates an expected call of GetTaskByID.
func (mr *MockModelInterfaceMockRecorder) GetTaskByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTaskByID", reflect.TypeOf((*MockModelInterface)(nil).GetTaskByID), ctx, id)
}

// GetTimeZone mocks base method.
func (m *MockModelInterface) GetTimeZone(ctx context.Context, id int32) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTimeZone", ctx, id)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTimeZone indicates an expected call of GetTimeZone.
func (mr *MockModelInterfaceMockRecorder) GetTimeZone(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTimeZone", reflect.TypeOf((*MockModelInterface)(nil).GetTimeZone), ctx, id)
}

// GetUser mocks base method.
func (m *MockModelInterface) GetUser(ctx context.Context, id int32) (*querier.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUser", ctx, id)
	ret0, _ := ret[0].(*querier.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUser indicates an expected call of GetUser.
func (mr *MockModelInterfaceMockRecorder) GetUser(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockModelInterface)(nil).GetUser), ctx, id)
}

// GetUserByName mocks base method.
func (m *MockModelInterface) GetUserByName(ctx context.Context, name string) (*querier.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByName", ctx, name)
	ret0, _ := ret[0].(*querier.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByName indicates an expected call of GetUserByName.
func (mr *MockModelInterfaceMockRecorder) GetUserByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByName", reflect.TypeOf((*MockModelInterface)(nil).GetUserByName), ctx, name)
}

// InTransaction mocks base method.
func (m *MockModelInterface) InTransaction() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InTransaction")
	ret0, _ := ret[0].(bool)
	return ret0
}

// InTransaction indicates an expected call of InTransaction.
func (mr *MockModelInterfaceMockRecorder) InTransaction() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InTransaction", reflect.TypeOf((*MockModelInterface)(nil).InTransaction))
}

// InitCluster mocks base method.
func (m *MockModelInterface) InitCluster(ctx context.Context, arg querier.InitClusterParams) (*querier.Cluster, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InitCluster", ctx, arg)
	ret0, _ := ret[0].(*querier.Cluster)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InitCluster indicates an expected call of InitCluster.
func (mr *MockModelInterfaceMockRecorder) InitCluster(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitCluster", reflect.TypeOf((*MockModelInterface)(nil).InitCluster), ctx, arg)
}

// InitDatabaseConnection mocks base method.
func (m *MockModelInterface) InitDatabaseConnection(ctx context.Context, arg querier.InitDatabaseConnectionParams) (*querier.DatabaseConnection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InitDatabaseConnection", ctx, arg)
	ret0, _ := ret[0].(*querier.DatabaseConnection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InitDatabaseConnection indicates an expected call of InitDatabaseConnection.
func (mr *MockModelInterfaceMockRecorder) InitDatabaseConnection(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitDatabaseConnection", reflect.TypeOf((*MockModelInterface)(nil).InitDatabaseConnection), ctx, arg)
}

// InsertEvent mocks base method.
func (m *MockModelInterface) InsertEvent(ctx context.Context, spec apigen.EventSpec) (*querier.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertEvent", ctx, spec)
	ret0, _ := ret[0].(*querier.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertEvent indicates an expected call of InsertEvent.
func (mr *MockModelInterfaceMockRecorder) InsertEvent(ctx, spec any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertEvent", reflect.TypeOf((*MockModelInterface)(nil).InsertEvent), ctx, spec)
}

// ListClusterDiagnostics mocks base method.
func (m *MockModelInterface) ListClusterDiagnostics(ctx context.Context, clusterID int32) ([]*querier.ListClusterDiagnosticsRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListClusterDiagnostics", ctx, clusterID)
	ret0, _ := ret[0].([]*querier.ListClusterDiagnosticsRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListClusterDiagnostics indicates an expected call of ListClusterDiagnostics.
func (mr *MockModelInterfaceMockRecorder) ListClusterDiagnostics(ctx, clusterID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListClusterDiagnostics", reflect.TypeOf((*MockModelInterface)(nil).ListClusterDiagnostics), ctx, clusterID)
}

// ListClusterSnapshots mocks base method.
func (m *MockModelInterface) ListClusterSnapshots(ctx context.Context, clusterID int32) ([]*querier.ClusterSnapshot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListClusterSnapshots", ctx, clusterID)
	ret0, _ := ret[0].([]*querier.ClusterSnapshot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListClusterSnapshots indicates an expected call of ListClusterSnapshots.
func (mr *MockModelInterfaceMockRecorder) ListClusterSnapshots(ctx, clusterID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListClusterSnapshots", reflect.TypeOf((*MockModelInterface)(nil).ListClusterSnapshots), ctx, clusterID)
}

// ListClustersByMetricsStoreID mocks base method.
func (m *MockModelInterface) ListClustersByMetricsStoreID(ctx context.Context, metricsStoreID *int32) ([]*querier.Cluster, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListClustersByMetricsStoreID", ctx, metricsStoreID)
	ret0, _ := ret[0].([]*querier.Cluster)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListClustersByMetricsStoreID indicates an expected call of ListClustersByMetricsStoreID.
func (mr *MockModelInterfaceMockRecorder) ListClustersByMetricsStoreID(ctx, metricsStoreID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListClustersByMetricsStoreID", reflect.TypeOf((*MockModelInterface)(nil).ListClustersByMetricsStoreID), ctx, metricsStoreID)
}

// ListMetricsStoresByOrgID mocks base method.
func (m *MockModelInterface) ListMetricsStoresByOrgID(ctx context.Context, organizationID int32) ([]*querier.MetricsStore, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMetricsStoresByOrgID", ctx, organizationID)
	ret0, _ := ret[0].([]*querier.MetricsStore)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMetricsStoresByOrgID indicates an expected call of ListMetricsStoresByOrgID.
func (mr *MockModelInterfaceMockRecorder) ListMetricsStoresByOrgID(ctx, organizationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMetricsStoresByOrgID", reflect.TypeOf((*MockModelInterface)(nil).ListMetricsStoresByOrgID), ctx, organizationID)
}

// ListOrgClusters mocks base method.
func (m *MockModelInterface) ListOrgClusters(ctx context.Context, organizationID int32) ([]*querier.Cluster, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOrgClusters", ctx, organizationID)
	ret0, _ := ret[0].([]*querier.Cluster)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListOrgClusters indicates an expected call of ListOrgClusters.
func (mr *MockModelInterfaceMockRecorder) ListOrgClusters(ctx, organizationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOrgClusters", reflect.TypeOf((*MockModelInterface)(nil).ListOrgClusters), ctx, organizationID)
}

// ListOrgDatabaseConnections mocks base method.
func (m *MockModelInterface) ListOrgDatabaseConnections(ctx context.Context, organizationID int32) ([]*querier.DatabaseConnection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOrgDatabaseConnections", ctx, organizationID)
	ret0, _ := ret[0].([]*querier.DatabaseConnection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListOrgDatabaseConnections indicates an expected call of ListOrgDatabaseConnections.
func (mr *MockModelInterfaceMockRecorder) ListOrgDatabaseConnections(ctx, organizationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOrgDatabaseConnections", reflect.TypeOf((*MockModelInterface)(nil).ListOrgDatabaseConnections), ctx, organizationID)
}

// ListOrganizations mocks base method.
func (m *MockModelInterface) ListOrganizations(ctx context.Context) ([]*querier.Organization, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOrganizations", ctx)
	ret0, _ := ret[0].([]*querier.Organization)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListOrganizations indicates an expected call of ListOrganizations.
func (mr *MockModelInterfaceMockRecorder) ListOrganizations(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOrganizations", reflect.TypeOf((*MockModelInterface)(nil).ListOrganizations), ctx)
}

// ListSnapshots mocks base method.
func (m *MockModelInterface) ListSnapshots(ctx context.Context, clusterID int32) ([]*querier.Snapshot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSnapshots", ctx, clusterID)
	ret0, _ := ret[0].([]*querier.Snapshot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSnapshots indicates an expected call of ListSnapshots.
func (mr *MockModelInterfaceMockRecorder) ListSnapshots(ctx, clusterID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSnapshots", reflect.TypeOf((*MockModelInterface)(nil).ListSnapshots), ctx, clusterID)
}

// PullTask mocks base method.
func (m *MockModelInterface) PullTask(ctx context.Context) (*querier.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PullTask", ctx)
	ret0, _ := ret[0].(*querier.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PullTask indicates an expected call of PullTask.
func (mr *MockModelInterfaceMockRecorder) PullTask(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PullTask", reflect.TypeOf((*MockModelInterface)(nil).PullTask), ctx)
}

// RemoveClusterMetricsStoreID mocks base method.
func (m *MockModelInterface) RemoveClusterMetricsStoreID(ctx context.Context, arg querier.RemoveClusterMetricsStoreIDParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveClusterMetricsStoreID", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveClusterMetricsStoreID indicates an expected call of RemoveClusterMetricsStoreID.
func (mr *MockModelInterfaceMockRecorder) RemoveClusterMetricsStoreID(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveClusterMetricsStoreID", reflect.TypeOf((*MockModelInterface)(nil).RemoveClusterMetricsStoreID), ctx, arg)
}

// RunTransaction mocks base method.
func (m *MockModelInterface) RunTransaction(ctx context.Context, f func(ModelInterface) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunTransaction", ctx, f)
	ret0, _ := ret[0].(error)
	return ret0
}

// RunTransaction indicates an expected call of RunTransaction.
func (mr *MockModelInterfaceMockRecorder) RunTransaction(ctx, f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunTransaction", reflect.TypeOf((*MockModelInterface)(nil).RunTransaction), ctx, f)
}

// SetTimeZone mocks base method.
func (m *MockModelInterface) SetTimeZone(ctx context.Context, arg querier.SetTimeZoneParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetTimeZone", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetTimeZone indicates an expected call of SetTimeZone.
func (mr *MockModelInterfaceMockRecorder) SetTimeZone(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTimeZone", reflect.TypeOf((*MockModelInterface)(nil).SetTimeZone), ctx, arg)
}

// UpdateAutoBackupConfig mocks base method.
func (m *MockModelInterface) UpdateAutoBackupConfig(ctx context.Context, arg querier.UpdateAutoBackupConfigParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAutoBackupConfig", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAutoBackupConfig indicates an expected call of UpdateAutoBackupConfig.
func (mr *MockModelInterfaceMockRecorder) UpdateAutoBackupConfig(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAutoBackupConfig", reflect.TypeOf((*MockModelInterface)(nil).UpdateAutoBackupConfig), ctx, arg)
}

// UpdateAutoDiagnosticsConfig mocks base method.
func (m *MockModelInterface) UpdateAutoDiagnosticsConfig(ctx context.Context, arg querier.UpdateAutoDiagnosticsConfigParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAutoDiagnosticsConfig", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAutoDiagnosticsConfig indicates an expected call of UpdateAutoDiagnosticsConfig.
func (mr *MockModelInterfaceMockRecorder) UpdateAutoDiagnosticsConfig(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAutoDiagnosticsConfig", reflect.TypeOf((*MockModelInterface)(nil).UpdateAutoDiagnosticsConfig), ctx, arg)
}

// UpdateMetricsStore mocks base method.
func (m *MockModelInterface) UpdateMetricsStore(ctx context.Context, arg querier.UpdateMetricsStoreParams) (*querier.MetricsStore, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMetricsStore", ctx, arg)
	ret0, _ := ret[0].(*querier.MetricsStore)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateMetricsStore indicates an expected call of UpdateMetricsStore.
func (mr *MockModelInterfaceMockRecorder) UpdateMetricsStore(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMetricsStore", reflect.TypeOf((*MockModelInterface)(nil).UpdateMetricsStore), ctx, arg)
}

// UpdateOrgCluster mocks base method.
func (m *MockModelInterface) UpdateOrgCluster(ctx context.Context, arg querier.UpdateOrgClusterParams) (*querier.Cluster, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOrgCluster", ctx, arg)
	ret0, _ := ret[0].(*querier.Cluster)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateOrgCluster indicates an expected call of UpdateOrgCluster.
func (mr *MockModelInterfaceMockRecorder) UpdateOrgCluster(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrgCluster", reflect.TypeOf((*MockModelInterface)(nil).UpdateOrgCluster), ctx, arg)
}

// UpdateOrgDatabaseConnection mocks base method.
func (m *MockModelInterface) UpdateOrgDatabaseConnection(ctx context.Context, arg querier.UpdateOrgDatabaseConnectionParams) (*querier.DatabaseConnection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOrgDatabaseConnection", ctx, arg)
	ret0, _ := ret[0].(*querier.DatabaseConnection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateOrgDatabaseConnection indicates an expected call of UpdateOrgDatabaseConnection.
func (mr *MockModelInterfaceMockRecorder) UpdateOrgDatabaseConnection(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrgDatabaseConnection", reflect.TypeOf((*MockModelInterface)(nil).UpdateOrgDatabaseConnection), ctx, arg)
}

// UpdateOrganization mocks base method.
func (m *MockModelInterface) UpdateOrganization(ctx context.Context, arg querier.UpdateOrganizationParams) (*querier.Organization, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOrganization", ctx, arg)
	ret0, _ := ret[0].(*querier.Organization)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateOrganization indicates an expected call of UpdateOrganization.
func (mr *MockModelInterfaceMockRecorder) UpdateOrganization(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrganization", reflect.TypeOf((*MockModelInterface)(nil).UpdateOrganization), ctx, arg)
}

// UpdateTask mocks base method.
func (m *MockModelInterface) UpdateTask(ctx context.Context, arg querier.UpdateTaskParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTask", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTask indicates an expected call of UpdateTask.
func (mr *MockModelInterfaceMockRecorder) UpdateTask(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTask", reflect.TypeOf((*MockModelInterface)(nil).UpdateTask), ctx, arg)
}

// UpdateTaskStartedAt mocks base method.
func (m *MockModelInterface) UpdateTaskStartedAt(ctx context.Context, arg querier.UpdateTaskStartedAtParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTaskStartedAt", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTaskStartedAt indicates an expected call of UpdateTaskStartedAt.
func (mr *MockModelInterfaceMockRecorder) UpdateTaskStartedAt(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTaskStartedAt", reflect.TypeOf((*MockModelInterface)(nil).UpdateTaskStartedAt), ctx, arg)
}

// UpdateTaskStatus mocks base method.
func (m *MockModelInterface) UpdateTaskStatus(ctx context.Context, arg querier.UpdateTaskStatusParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTaskStatus", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTaskStatus indicates an expected call of UpdateTaskStatus.
func (mr *MockModelInterfaceMockRecorder) UpdateTaskStatus(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTaskStatus", reflect.TypeOf((*MockModelInterface)(nil).UpdateTaskStatus), ctx, arg)
}

// UpsertRefreshToken mocks base method.
func (m *MockModelInterface) UpsertRefreshToken(ctx context.Context, arg querier.UpsertRefreshTokenParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertRefreshToken", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertRefreshToken indicates an expected call of UpsertRefreshToken.
func (mr *MockModelInterfaceMockRecorder) UpsertRefreshToken(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertRefreshToken", reflect.TypeOf((*MockModelInterface)(nil).UpsertRefreshToken), ctx, arg)
}
