// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package querier

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/risingwavelabs/wavekit/internal/apigen"
)

type AutoBackupConfig struct {
	ClusterID      int32
	Enabled        bool
	CronExpression string
	KeepLast       int32
	CreatedAt      time.Time
	UpdatedAt      time.Time
	NextTaskID     int32
}

type AutoBackupTask struct {
	ClusterID  int32
	NextTaskID int32
}

type AutoDiagnosticsConfig struct {
	ClusterID         int32
	Enabled           bool
	CronExpression    string
	RetentionDuration *string
	CreatedAt         time.Time
	UpdatedAt         time.Time
	NextTaskID        int32
}

type AutoDiagnosticsTask struct {
	ClusterID  int32
	NextTaskID int32
}

type Cluster struct {
	ID             int32
	OrganizationID int32
	Name           string
	Host           string
	SqlPort        int32
	MetaPort       int32
	HttpPort       int32
	Version        string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	MetricsStoreID *int32
}

type ClusterDiagnostic struct {
	ID        int32
	ClusterID int32
	Content   string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type ClusterSnapshot struct {
	ClusterID  int32
	SnapshotID int64
	Name       string
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type DatabaseConnection struct {
	ID             int32
	OrganizationID int32
	Name           string
	ClusterID      int32
	Username       string
	Password       *string
	Database       string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type Event struct {
	ID        int32
	Spec      apigen.EventSpec
	CreatedAt time.Time
}

type MetricsStore struct {
	ID             int32
	Name           string
	Spec           *apigen.MetricsStoreSpec
	OrganizationID int32
	DefaultLabels  *apigen.MetricsStoreLabelMatcherList
	CreatedAt      pgtype.Timestamp
	UpdatedAt      pgtype.Timestamp
}

type OrgSetting struct {
	OrganizationID int32
	Timezone       string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type Organization struct {
	ID        int32
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
	Timezone  string
}

type OrganizationOwner struct {
	UserID         int32
	OrganizationID int32
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type RefreshToken struct {
	ID        int32
	UserID    int32
	Token     string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Snapshot struct {
	ClusterID  int32
	SnapshotID int64
	CreatedAt  time.Time
}

type Task struct {
	ID         int32
	Attributes apigen.TaskAttributes
	Spec       apigen.TaskSpec
	Status     string
	Timeout    pgtype.Interval
	StartedAt  *time.Time
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type User struct {
	ID             int32
	Name           string
	PasswordHash   string
	PasswordSalt   string
	OrganizationID int32
	CreatedAt      time.Time
	UpdatedAt      time.Time
}
