// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: orgs.sql

package querier

import (
	"context"
)

const getTimeZone = `-- name: GetTimeZone :one
SELECT timezone
FROM organizations
WHERE id = $1
`

func (q *Queries) GetTimeZone(ctx context.Context, id int32) (string, error) {
	row := q.db.QueryRow(ctx, getTimeZone, id)
	var timezone string
	err := row.Scan(&timezone)
	return timezone, err
}

const setTimeZone = `-- name: SetTimeZone :exec
UPDATE organizations
SET timezone = $2
WHERE id = $1
`

type SetTimeZoneParams struct {
	ID       int32
	Timezone string
}

func (q *Queries) SetTimeZone(ctx context.Context, arg SetTimeZoneParams) error {
	_, err := q.db.Exec(ctx, setTimeZone, arg.ID, arg.Timezone)
	return err
}
